[package]
edition = "2024"
name = "callback-hook"
version = "0.1.0"

[[bin]]
name = "callback-hook"
path = "bin.rs"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }


